<a href="https://colab.research.google.com/github/Abhishek2104200/CUBE_AI/blob/main/car_prediction_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [5]:
df=pd.read_csv('/car_prices.csv')

In [6]:
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Nissan,Altima,2.5 S,Sedan,automatic,1n4al3ap5fc124223,ca,2.0,11398.0,black,black,enterprise vehicle exchange / tra / rental / t...,14750.0,14100.0,Tue Dec 23 2014 12:00:00 GMT-0800 (PST)
1,2014,Audi,Q5,2.0T Premium Plus quattro,SUV,automatic,wa1lfafpxea085074,ca,49.0,7983.0,white,black,audi north scottsdale,37100.0,40000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
2,2014,Chevrolet,Camaro,LS,Coupe,automatic,2g1fa1e39e9134494,ca,17.0,13441.0,black,black,wells fargo dealer services,17750.0,17000.0,Tue Dec 30 2014 15:00:00 GMT-0800 (PST)
3,2014,BMW,6 Series,650i,Convertible,automatic,wbayp9c53ed169260,ca,34.0,8819.0,black,black,the hertz corporation,68000.0,67200.0,Wed Dec 17 2014 12:30:00 GMT-0800 (PST)
4,2015,Chevrolet,Impala,LTZ,Sedan,automatic,2g1165s30f9103921,ca,19.0,14538.0,silver,black,enterprise vehicle exchange / tra / rental / t...,24300.0,7200.0,Tue Jul 07 2015 09:30:00 GMT-0700 (PDT)

In [ ]:
df['make'].unique()

array(['Nissan', 'Audi', 'Chevrolet', 'BMW', 'Volvo', 'Kia', 'Cadillac',
       'Acura', 'Lexus', 'Hyundai', 'Buick', 'Ford', 'Infiniti', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Mazda', 'MINI', 'Land Rover',
       'Lincoln', 'Jaguar', 'Volkswagen', 'Toyota', 'Subaru', 'Scion',
       'Porsche', 'Dodge', 'FIAT', 'Chrysler', 'Ferrari', 'Honda', 'GMC',
       'Ram', 'smart', 'Bentley', 'Pontiac', 'Saturn', 'Maserati',
       'Mercury', 'HUMMER', 'Saab', 'Suzuki', 'Oldsmobile', 'Rolls-Royce',
       'Isuzu', 'Plymouth', 'Tesla', 'Aston Martin', 'Geo', 'Fisker',
       'Daewoo', 'Lamborghini', 'Lotus'], dtype=object)

In [ ]:
df['color'].unique()

array(['black', 'white', 'silver', 'gray', 'brown', 'beige', 'red',
       'blue', 'purple', 'burgundy', '—', 'gold', 'yellow', 'green',
       'charcoal', 'orange', 'off-white', 'turquoise', 'pink', 'lime'],
      dtype=object)

In [ ]:
df['model'].unique()

array(['Altima', 'Q5', 'Camaro', '6 Series', 'Impala', '5 Series', 'A3',
       'XC70', 'Cruze', 'SQ5', 'Sorento', 'S5', 'Suburban', '3 Series',
       'M5', 'ELR', 'V60', 'X6', 'ILX', '6 Series Gran Coupe', 'K900',
       'Malibu', 'RX 350', 'Versa', 'Elantra', 'Versa Note', 'A8', 'X1',
       'Enclave', 'TTS', '4 Series', 'MDX', 'Fusion', 'Silverado 1500',
       'SRX', 'X5', 'G Coupe', 'G Sedan', 'FX', 'Santa Fe', 'Genesis',
       'Equus', 'Sonata', 'Sonata Hybrid', 'Accent', 'Veloster',
       'Elantra Coupe', 'Azera', 'Tucson', 'Genesis Coupe', 'Wrangler',
       'Optima', 'S-Class', 'GS 350', 'Outlander', 'C-Class', 'Mazda2',
       'Rio', 'M', '370Z', 'Soul', 'Outlander Sport', 'SLK-Class',
       'ES 350', 'E-Class', 'Mazda3', 'Cooper Clubman', 'Cooper', 'CX-9',
       'Forte', 'Compass', 'JX', 'LR4', 'Mazda5', 'Range Rover Evoque',
       'LS 460', 'GLK-Class', 'Sportage', 'Grand Cherokee', 'MKX', 'XF',
       'GL-Class', 'M-Class', 'Cooper Countryman', 'Lancer',
       'Range Rover Sport', 'Passat', 'Corolla', 'XC60', 'Sienna', 'Juke',
       'Yaris', 'NV', 'CC', 'Leaf', 'Camry', 'Tacoma', 'Jetta',
       'Impreza WRX', 'FJ Cruiser', 'Beetle', 'Avalon', 'FR-S', 'NV200',
       'Rogue', 'Tundra', 'Maxima', 'Cayenne', '911', 'Xterra', 'Sentra',
       'Prius', 'S80', 'Frontier', 'Boxster', 'Camry Hybrid', 'xB',
       'Cube', 'Jetta SportWagen', '4Runner', 'Sequoia', 'S60', 'Legacy',
       'Armada', 'Venza', 'Pathfinder', 'Panamera', 'Forester',
       'Highlander', 'Murano', 'TSX', 'A6', '7 Series', '1 Series', 'TL',
       'S4', 'A7', 'A5', 'M3', 'Cooper Coupe', 'RDX', 'ZDX', 'A4', 'R8',
       'X3', 'Avenger', 'Escape', 'Edge', 'Focus', 'Z4', 'Traverse',
       'Silverado 2500HD', 'F-350 Super Duty', 'Fiesta', '500', '200',
       'Journey', 'Charger', 'Flex', 'Equinox', '300', 'Explorer',
       'Captiva Sport', 'Escalade', 'Grand Caravan', 'CTS Coupe', 'F-150',
       'E-Series Van', 'Volt', 'E-Series Wagon', 'Express Cargo', 'X5 M',
       'Expedition', 'Colorado', 'Express', 'California', 'Escalade ESV',
       'Town and Country', 'Sonic', 'Accord', 'CR-V', 'Mustang', 'Civic',
       'Fit', 'Pilot', 'Odyssey', 'Crosstour', 'Transit Connect',
       'Terrain', 'Taurus', 'G Convertible', 'Yukon', 'Veracruz', 'XJ',
       'Liberty', 'IS 250', 'XK', 'QX', 'CT 200h', 'Mazda6', 'MKZ',
       'Navigator', 'Range Rover', 'SL-Class', 'Sedona', 'IS 350',
       'Patriot', '1500', 'Impreza', 'GT-R', 'tC', '2500', 'Galant',
       'fortwo', 'GLI', '5 Series Gran Turismo', 'XC90', 'Tiguan', 'GTI',
       'Q7', 'Highlander Hybrid', 'RAV4', 'Prius Plug-in', 'CR-Z', 'EX',
       'Sierra 1500', 'LaCrosse', 'HHR', 'Accord Crosstour', 'CTS',
       'Nitro', 'Tahoe', 'Challenger', 'CTS-V', 'Escape Hybrid', 'X6 M',
       'Ranger', 'Insight', 'Fusion Hybrid', 'CTS-V Coupe',
       'F-250 Super Duty', 'Acadia', 'Impala Limited', 'Dart', 'M37',
       'Sprinter', 'Town Car', 'RX 450h', 'MKT', 'QX56', 'CX-7', 'Aveo',
       'Outback', 'Caliber', 'Routan', 'Sebring', 'Corvette',
       'Continental GT Speed', 'malibu', 'Land Cruiser', 'V50',
       'Commander', 'Altima Hybrid', 'G37 Convertible', 'New Beetle',
       'Golf', 'LR2', 'Lancer Sportback', 'G5', 'Yukon XL',
       'Escalade Hybrid', 'Avalanche', 'Spectra', 'Rondo', 'Borrego',
       'G-Class', 'MKS', 'CLK-Class', 'Tahoe Hybrid', 'Econoline Cargo',
       'Econoline Wagon', 'CLS-Class', 'STS', 'Ridgeline',
       'F-450 Super Duty', 'Magnum', 'Durango', 'S40', 'Malibu Classic',
       'TT', 'Explorer Sport Trac', 'Ram Pickup 1500', 'PT Cruiser',
       'Pacifica', 'S6', 'Rabbit', 'Sierra 2500HD', 'C30', 'VUE',
       'GranTurismo', 'G6', 'Grand Prix', '350Z', 'Raider',
       'Mazdaspeed Mazda3', 'Solstice', 'Milan', 'GX 470', 'RX 400h',
       'Titan', 'H3', 'CL-Class', 'Outlook', 'G37', 'IS F', 'Touareg 2',
       'Lancer Evolution', 'G35', 'xD', 'XJ-Series', 'Cobalt', 'H2',
       'DTS', 'M45', 'Uplander', 'GS 450h', 'Silverado 1500 Classic',
       'Rendezvous', 'FX35', 'ION', 'R-Class', 'Eclipse', 'Aura', 'RSX',
       'Five Hundred', 'Envoy XL', 'S-Type', 'Continental Flying Spur',
       'S2000', 'FX45', 'Element', 'Monte Carlo', 'Cayman S', 'Mark LT',
       'GS 300', 'Camry Solara', 'Touareg', 'allroad quattro', '09-Mar',
       '500L', 'Sprinter Cargo', 'DeVille', 'H2 SUT', 'TrailBlazer',
       'Canyon', 'Dakota', 'Continental GT', 'Neon', 'ES 330',
       'Freestyle', 'Stratus', 'Q45', 'Freestar', 'Quest', 'XLR',
       'Aviator', 'LS 430', 'RX 330', 'SC 430', 'Envoy XUV', 'Monterey',
       'Ram Pickup 3500', 'Excursion', 'Mountaineer', 'Malibu Maxx',
       'Celica', 'Grand Am', 'Matrix', 'Envoy', 'Endeavor', 'Concorde',
       'Marauder', 'C70', 'LS', 'Blazer', 'LeSabre', 'MPV', 'Montero',
       'ES 300', 'Thunderbird', 'Century', 'Cavalier', 'Venture', 'S-10',
       'XL-7', 'Silverado 1500HD', 'Savana Cargo', 'X-Type', 'Sonoma',
       'IS 300', 'Protege5', 'Alero', 'Grand Vitara', 'RX 300',
       'L-Series', 'Intrigue', 'XC', 'S-Series', 'Discovery Series II',
       'QX4', 'Continental', 'Seville', 'Park Avenue', 'Millenia', 'V70',
       'Z3', 'LHS', 'Regal', 'G20', 'Eldorado', 'Intrepid', 'Contour',
       'S90', 'I30', 'Sunfire', 'Escort', 'Mustang SVT Cobra',
       'Grand Marquis', 'LS 400', 'Cutlass Ciera', 'Santa Fe Sport',
       'Cherokee', 'Cadenza', 'Q50', 'Elantra GT', 'F-TYPE',
       'Shelby GT500', 'QX70', 'QX60', 'Q60 Convertible',
       'Cooper Roadster', 'CX-5', 'Cooper Paceman', 'MX-5 Miata',
       'Rogue Select', 'Cayman', 'CLA-Class', 'allroad', 'ATS', 'Prius v',
       'Continental GTC', 'XV Crosstrek', 'C-Max Energi', 'C-Max Hybrid',
       'Spark', 'RS 7', 'GX 460', 'CTS Wagon', 'SLS AMG',
       'Ram Pickup 2500', 'Eclipse Spyder', 'Vibe', 'Eos', 'Caravan',
       'Mariner', 'SSR', 'Safari Cargo', 'Amanti', 'Tribute', 'Sable',
       'Phaeton', 'R32', '09-May', 'Truck', 'Tercel', 'Roadmaster',
       'SC 400', 'LX 570', 'QX80', 'RS 5', 'Jetta GLI', 'ES 300h', 'M4',
       'SX4', 'iQ', '3500', 'Kizashi', 'C/V Cargo Van', 'Prius c',
       'Lucerne', 'Silverado 3500HD', 'Crown Victoria', 'Sierra 3500HD',
       'M56', 'RL', 'ActiveHybrid X6', 'M35', 'Elantra Touring',
       'G37 Coupe', 'HS 250h', 'Mazdaspeed3', 'Milan Hybrid', 'Ghost',
       'Silverado 1500 Hybrid', 'Aspen', 'Taurus X', '6',
       'Mariner Hybrid', 'G8', 'Torrent', 'VUE Hybrid', 'G3', '9-7X',
       'Expedition EL', 'Yukon Hybrid', 'Tiburon', 'LR3', 'Astra',
       'Tribeca', 'XL7', 'Forenza', 'Sky', 'M6', 'S8', 'Terraza',
       'Silverado 2500HD Classic', 'Focus ST', 'Fusion Energi',
       'Entourage', 'B-Series Truck', 'Mazdaspeed Mazda6', 'Montego',
       'B9 Tribeca', 'Escalade EXT', 'Rainier', 'Silverado 3500',
       'Crossfire', 'TrailBlazer EXT', 'Sierra 1500HD', 'Savana',
       'Zephyr', 'Quattroporte', 'Relay', 'Verona', 'Classic', 'XG350',
       'Q60 Coupe', 'Q70', 'QX50', 'GTO', 'Bonneville', 'Baja', 'ECHO',
       'Silverado 2500', '300M', 'F-150 Heritage', 'accord', 'Rodeo',
       'Ascender', 'Freelander', 'L300', 'MR2 Spyder', 'RS 6', 'Tracker',
       'Explorer Sport', 'Axiom', 'Montero Sport', 'Diamante', 'Prizm',
       'Windstar', 'Protege', 'Firebird', 'Silhouette', 'Aurora', 'CL',
       'Astro', '626', 'GS 430', 'Prowler', 'Aztek', 'Cabrio', 'Integra',
       'Tahoe Limited/Z71', 'Cirrus', 'LX 470', 'Mirage', 'S70', 'Catera',
       'Passport', 'Cougar', 'C/K 1500 Series', 'Discovery', 'XK-Series',
       'Bravada', 'B-Series Pickup', 'SC 300', 'Lumina', 'Pickup',
       '500-Class', 'Murano CrossCabriolet', 'Jetta Hybrid', 'S7',
       'Encore', 'Verano', 'XTS', 'Black Diamond Avalanche', 'RLX',
       '2 Series', 'M6 Gran Coupe', 'C/V Tradesman', 'BRZ', 'Model S',
       'Beetle Convertible', 'Golf R', 'TSX Sport Wagon',
       'Corvette Stingray', 'SS', 'IS 250 C', 'Mazdaspeed 3', 'i-MiEV',
       'F430', 'I35', 'Cutlass Supreme', 'IS 350 C', 'EX35', 'Reno',
       'Astro Cargo', 'Montana', 'Aerio', 'Mazdaspeed MX-5 Miata', 'V40',
       'Safari', 'Ram Cargo', 'envoy', 'Prelude', '200SX', 'Eighty-Eight',
       'Legend', '850', 'Promaster Cargo Van', 'Sephia', 'Jimmy',
       'Malibu Hybrid', 'Sierra 1500 Classic', 'Rodeo Sport', 'Cutlass',
       'Spirit', '300-Class', 'Accord Hybrid', 'NV Cargo',
       '3 Series Gran Turismo', 'Viper', 'Sierra 2500', 'Trooper',
       'Yukon Denali', 'Avalon Hybrid', 'RX-8', 'V8 Vantage', 'Equator',
       'Sierra 2500HD Classic', '9-2X', 'xA', 'XG300', 'C/K 3500 Series',
       'Mark VIII', 'GranTurismo Convertible', 'Voyager', 'GS 400',
       'Caprice', 'Eighty-Eight Royale', 'ActiveHybrid 7', 'GS 460',
       'Tribute Hybrid', 'Aura Hybrid', 'Golf GTI', 'i-Series',
       'MKZ Hybrid', 'Macan', 'FX50', 'STS-V', 'Ghibli', 'CTS-V Wagon',
       'Karma', 'Navigator L', 'Z4 M', 'Villager', 'Coupe', 'Ram Van',
       'Tempo', 'Blackwood', 'Tracer', 'CV Tradesman', 'DB9',
       'C/K 2500 Series', 'i8', 'Rapide', 'Nubira', 'Mazdaspeed Protege',
       '960', 'Montana SV6', 'Corsica', 'NV Passenger', 'Spyder',
       'LS 600h L', '400-Class', 'J30', 'H3T', 'Vitara', 'LX 450', 'WRX',
       'Silverado 3500 Classic', 'GranSport', '500e',
       'Continental Supersports', 'EuroVan', 'Windstar Cargo', '3',
       'Sierra 3500', 'Esteem', 'Mystique', 'F-150 SVT Lightning',
       'E-150', 'Breeze', 'Riviera', '190-Class', 'MKC', 'Aspire', '940',
       'Gallardo', 'Amigo', 'Continental Flying Spur Speed', '3000GT',
       'TT RS', '300ZX', 'ActiveHybrid 5', 'Sierra 1500 Hybrid',
       'ML55 AMG', 'S-10 Blazer', 'RS 4', 'T100', 'Continental GTC Speed',
       'Transit Van', 'Sidekick', 'E-250', '8 Series', '420-Class',
       'Achieva', 'B-Class Electric Drive', 'Paseo', 'Civic del Sol',
       'Exige', 'X4', 'Spark EV', 'Transit Wagon', 'H1', 'SLS AMG GT',
       'mdx', 'Metro', 'Grand Cherokee SRT', 'RC F', 'Q3',
       '4 Series Gran Coupe', 'RC 350', 'E-350', '360', 'GLA-Class',
       'TLX', '458 Italia'], dtype=object)

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [9]:
drop_feat=['trim','vin','state','condition','interior','seller','saledate']
df.drop(['trim','vin','state','condition','interior','seller','saledate'],axis=1,inplace=True)

In [10]:
df.head()

,year,make,model,body,transmission,odometer,color,mmr,sellingprice
0,2015,Nissan,Altima,Sedan,automatic,11398.0,black,14750.0,14100.0
1,2014,Audi,Q5,SUV,automatic,7983.0,white,37100.0,40000.0
2,2014,Chevrolet,Camaro,Coupe,automatic,13441.0,black,17750.0,17000.0
3,2014,BMW,6 Series,Convertible,automatic,8819.0,black,68000.0,67200.0
4,2015,Chevrolet,Impala,Sedan,automatic,14538.0,silver,24300.0,7200.0

In [11]:
category=['make','model','body','transmission','color']
ohe_trans=ohe.fit_transform(df[category])

In [ ]:
ohe_trans

,make_Acura,make_Aston Martin,make_Audi,make_BMW,make_Bentley,make_Buick,make_Cadillac,make_Chevrolet,make_Chrysler,make_Daewoo,...,color_off-white,color_orange,color_pink,color_purple,color_red,color_silver,color_turquoise,color_white,color_yellow,color_—
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472306,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
472307,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
472308,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
472309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
472310,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.columns

Index(['year', 'make', 'model', 'body', 'transmission', 'odometer', 'color',
       'mmr', 'sellingprice'],
      dtype='object')

In [12]:
df=pd.concat([df,ohe_trans],axis=1)

In [13]:
df

,year,make,model,body,transmission,odometer,color,mmr,sellingprice,make_Acura,...,color_orange,color_pink,color_purple,color_red,color_silver,color_turquoise,color_white,color_yellow,color_—,color_nan
0,2015,Nissan,Altima,Sedan,automatic,11398.0,black,14750.0,14100.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014,Audi,Q5,SUV,automatic,7983.0,white,37100.0,40000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2014,Chevrolet,Camaro,Coupe,automatic,13441.0,black,17750.0,17000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014,BMW,6 Series,Convertible,automatic,8819.0,black,68000.0,67200.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,Chevrolet,Impala,Sedan,automatic,14538.0,silver,24300.0,7200.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26205,2012,Chevrolet,Malibu,Sedan,automatic,57794.0,silver,10250.0,9300.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26206,2012,Chevrolet,Impala,Sedan,automatic,65406.0,black,9000.0,9300.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26207,2012,Chevrolet,Malibu,Sedan,automatic,46524.0,white,9650.0,9700.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
26208,2012,Dodge,Charger,Sedan,automatic,39115.0,gray,15600.0,13300.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26209,2012,Dodge,Avenger,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [48]:
df=df.drop(['make','model','transmission','color','body'],axis=1)

KeyError: "['make', 'model', 'transmission', 'color', 'body'] not found in axis"

In [47]:
test=df['sellingprice']

In [49]:
train=df

In [50]:
d='sellingprice'

In [51]:
train=train.drop(['sellingprice'],axis=1)

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [53]:
x_train,x_test,y_train,y_test=train_test_split(train,test,test_size=0.8,random_state=42)

In [54]:
model=LinearRegression()

In [55]:
model.fit(x_train,y_train)

LinearRegression()

In [56]:
x_test=x_test.dropna()

In [57]:
y_test=y_test.dropna()

In [58]:
model.predict(x_test)

array([ 8407.11511283,  6206.18458652,  5439.93817797, ...,
        3614.37724847, 14516.63596867,  7702.7908143 ])

In [59]:
model.score(x_test,y_test)

0.9619788908732494

In [60]:
train

,year,odometer,mmr,make_Acura,make_Audi,make_BMW,make_Bentley,make_Buick,make_Cadillac,make_Chevrolet,...,color_orange,color_pink,color_purple,color_red,color_silver,color_turquoise,color_white,color_yellow,color_—,color_nan
0,2015,11398.0,14750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014,7983.0,37100.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2014,13441.0,17750.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014,8819.0,68000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,14538.0,24300.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26205,2012,57794.0,10250.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26206,2012,65406.0,9000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26207,2012,46524.0,9650.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
26208,2012,39115.0,15600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26209,2012,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0